import { launch, ctx, VPS, goto, sleep, watch, touchTap } from "./juror6-lib.mjs";
const vpName = process.argv[2] || "p390"; const route = process.argv[3] || "/bakery";
const vp = VPS[vpName];
const browser = await launch(); const c = await ctx(browser, vp); const page = await c.newPage(); const log = watch(page);
await goto(page, route); await sleep(1500); await page.addStyleTag({ content: "html{scroll-behavior:auto !important}" });
const play = page.locator("button[aria-label^='Play narration']").first(); await play.scrollIntoViewIfNeeded(); await sleep(300); await play.click(); await sleep(2000);
const A = () => page.evaluate(() => { const a = document.querySelector("audio"); const act = document.querySelector("#scene-0 p.narration-active"); return { t: Math.round(a.currentTime * 10) / 10, paused: a.paused, active: act && act.innerText.slice(0, 30) }; });
console.log("playing:", JSON.stringify(await A()));
const ps = page.locator("#scene-0 p.t-prose");
const n = await ps.count(); console.log("prose paragraphs:", n);
const target = ps.nth(Math.min(3, n - 1));
await target.scrollIntoViewIfNeeded(); await sleep(400);
const bb = await target.boundingBox();
if (vp.mobile) await touchTap(page, bb.x + 60, bb.y + 20); else await page.mouse.click(bb.x + 60, bb.y + 20);
await sleep(1200);
console.log("after tap p[3]:", JSON.stringify(await A()));
const target2 = ps.nth(1); await target2.scrollIntoViewIfNeeded(); await sleep(300); const bb2 = await target2.boundingBox();
if (vp.mobile) await touchTap(page, bb2.x + 60, bb2.y + 20); else await page.mouse.click(bb2.x + 60, bb2.y + 20);
await sleep(1200);
console.log("after tap p[1]:", JSON.stringify(await A()));
console.log("errors", log.errors);
await browser.close();
